import mongoose from 'mongoose';

const MONGODB_URI = process.env.MONGODB_URI || '';

interface QuestionData {
  category: 'verbal' | 'quantitative' | 'general';
  subcategory: string;
  text: string;
  options: string[];
  correctOptionIndex: number;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  topic: string;
  explanation: string;
  keywords: string[];
}

// ===== أسئلة اللغة العربية =====
const arabicQuestions: QuestionData[] = [
  // النحو والصرف
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما إعراب كلمة "الطالبُ" في جملة: "جاء الطالبُ"؟', options: ['فاعل مرفوع', 'مبتدأ مرفوع', 'خبر مرفوع', 'مفعول به'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'النحو', explanation: 'كلمة "الطالب" فاعل للفعل "جاء" مرفوع وعلامة رفعه الضمة الظاهرة على آخره.', keywords: ['نحو', 'إعراب', 'فاعل'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما الفرق بين الفعل المتعدي والفعل اللازم؟', options: ['المتعدي يحتاج مفعولاً به، واللازم لا يحتاجه', 'المتعدي لا يحتاج مفعولاً به، واللازم يحتاجه', 'المتعدي يأتي للمجهول، واللازم لا يأتي', 'لا فرق بينهما'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'النحو', explanation: 'الفعل المتعدي هو الذي يحتاج إلى مفعول به ليتم معناه، أما اللازم فلا يحتاج إلى مفعول به.', keywords: ['نحو', 'فعل متعدي', 'فعل لازم'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما المقصود بـ"التوكيد المعنوي"؟', options: ['تقوية الحكم بألفاظ مخصوصة كالنفس والعين والكل والجميع', 'تكرار اللفظ لتقوية المعنى', 'الإتيان بضمير منفصل بعد المؤكَّد', 'لا شيء مما ذكر'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'النحو', explanation: 'التوكيد المعنوي يكون بألفاظ مخصوصة مثل: نفس، عين، كل، جميع، كلا، كلتا.', keywords: ['نحو', 'توكيد', 'توكيد معنوي'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'أي من التالي مثال على الاسم المنقوص؟', options: ['القاضي', 'الكتاب', 'الرجال', 'المدرسة'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الصرف', explanation: 'الاسم المنقوص هو الاسم المعرب الذي آخره ياء لازمة قبلها كسرة مثل: القاضي، الراضي.', keywords: ['صرف', 'اسم منقوص', 'ياء لازمة'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما جمع كلمة "شاعر"؟', options: ['شعراء', 'شواعر', 'شعراء وشواعر', 'شاعرون'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الصرف', explanation: 'جمع شاعر: شعراء على وزن فُعَلاء، وهو من أبنية جمع التكسير.', keywords: ['صرف', 'جمع تكسير', 'شاعر'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما الميزان الصرفي لكلمة "مكتبة"؟', options: ['مَفْعَلة', 'فَعَلة', 'مفعلة', 'فَعْلة'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الصرف', explanation: 'مكتبة: ميزانها الصرفي مَفْعَلة، والأصل: كتب، فالميم زائدة للمكان.', keywords: ['صرف', 'ميزان صرفي', 'مفعلة'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما نوع الأسلوب في الجملة: "يا أيها الطلابُ اجتهدوا"؟', options: ['نداء وأمر', 'نهي وترغيب', 'استفهام وتعجب', 'شرط وجزاء'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'البلاغة', explanation: 'الجملة تشمل أسلوب النداء "يا أيها الطلاب" وأسلوب الأمر "اجتهدوا".', keywords: ['أسلوب', 'نداء', 'أمر'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما المقصود بـ"الحال" في النحو العربي؟', options: ['وصف فضلة يبين هيئة صاحبه وقت وقوع الفعل', 'اسم مشتق يصف صاحبه', 'ما يدل على الجنس أو النوع', 'الاسم الذي يتم به الكلام'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'النحو', explanation: 'الحال وصف فضلة، منصوب، يبين هيئة صاحبه أو ما يشبهه وقت وقوع الفعل، مثل: جاء الطالب مسرعاً.', keywords: ['نحو', 'حال', 'منصوبات'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما جمع "مدير"؟', options: ['مديرون ومدراء', 'مديرون فقط', 'مدراء فقط', 'مدير لا يُجمع'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الصرف', explanation: 'مدير يُجمع جمع مذكر سالم فيصبح "مديرون" في الرفع و"مديرين" في النصب والجر، كما يُجمع جمع تكسير "مدراء".', keywords: ['صرف', 'جمع', 'مدير'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما أداة الاستفهام المناسبة في: "... تعلمتَ؟" (السؤال عن الزمن)', options: ['متى', 'أين', 'كيف', 'ماذا'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'النحو', explanation: 'متى: أداة استفهام تُستخدم للسؤال عن الزمن.', keywords: ['استفهام', 'أدوات', 'زمن'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما المفرد لكلمة "أطباء"؟', options: ['طبيب', 'طبيبة', 'طابع', 'طُبَّع'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الصرف', explanation: 'أطباء جمع تكسير ومفرده "طبيب" على وزن فَعيل.', keywords: ['صرف', 'مفرد', 'جمع تكسير'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما علامة نصب الاسم المفرد؟', options: ['الفتحة', 'الكسرة', 'الياء', 'الألف'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'النحو', explanation: 'الاسم المفرد يُنصب بالفتحة الظاهرة على آخره، مثل: رأيتُ طالباً.', keywords: ['نحو', 'علامات إعراب', 'نصب'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما المقصود بـ"الاستعارة" في البلاغة؟', options: ['تشبيه حُذف أحد طرفيه', 'المشابهة بين شيئين بأداة', 'المبالغة في وصف شيء', 'الجمع بين المتضادين'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'البلاغة', explanation: 'الاستعارة تشبيه بليغ حُذف أحد طرفيه (المشبه أو المشبه به) مع قرينة تمنع إرادة المعنى الحقيقي.', keywords: ['بلاغة', 'استعارة', 'تشبيه'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'أي الجمل التالية تحتوي على "تشبيه بليغ"؟', options: ['العلم نور', 'العلم كالنور', 'العلم مثل النور', 'العلم أشبه بالنور'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'البلاغة', explanation: 'التشبيه البليغ هو الذي حُذفت منه أداة التشبيه ووجه الشبه معاً، فيبقى المشبه والمشبه به فقط.', keywords: ['بلاغة', 'تشبيه بليغ', 'أنواع التشبيه'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما معنى "الجناس" في علم البديع؟', options: ['تشابه الألفاظ في اللفظ مع اختلافها في المعنى', 'تكرار المعنى بألفاظ مختلفة', 'الجمع بين شيئين متضادين', 'المبالغة في الوصف'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'البلاغة', explanation: 'الجناس هو اتفاق اللفظين في النطق مع اختلافهما في المعنى، وهو نوعان: تام وناقص.', keywords: ['بلاغة', 'بديع', 'جناس'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما المقصود بـ"الطباق"؟', options: ['الجمع بين الشيء وضده في الكلام', 'تكرار كلمة بلفظها ومعناها', 'تشابه العبارات في الإيقاع', 'المبالغة في المدح أو الذم'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'البلاغة', explanation: 'الطباق هو الجمع بين المتضادين أو الضدين في الكلام مثل: الليل والنهار، السواد والبياض.', keywords: ['بلاغة', 'طباق', 'بديع'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما وزن "فَعَّلَ"؟ أعطِ مثالاً.', options: ['درَّسَ، قدَّمَ', 'ذهبَ، جاءَ', 'انطلقَ، استعانَ', 'قرأَ، كتبَ'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الصرف', explanation: 'وزن فَعَّلَ يدل على التكثير والمبالغة في الفعل، مثل: درَّسَ بمعنى درَّس كثيراً، قدَّمَ.', keywords: ['صرف', 'وزن', 'فعّل'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما الفرق بين "الكناية" و"المجاز"؟', options: ['الكناية يصح فيها إرادة المعنى الحقيقي بخلاف المجاز', 'المجاز يصح فيه إرادة الحقيقة والكناية لا', 'لا فرق بينهما', 'الكناية في الأسماء والمجاز في الأفعال'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'البلاغة', explanation: 'الفرق الجوهري: في الكناية يمكن إرادة المعنى الحقيقي، بينما في المجاز لا يمكن ذلك لوجود قرينة تمنعه.', keywords: ['بلاغة', 'كناية', 'مجاز'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما نوع "لا" في جملة: "لا رجلَ في الدار"؟', options: ['لا النافية للجنس', 'لا الناهية', 'لا النافية للواحد', 'لا العاطفة'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'النحو', explanation: 'لا النافية للجنس تنفي الجنس كله ونصب اسمها بلا تنوين إذا كان مفرداً.', keywords: ['نحو', 'لا النافية', 'للجنس'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'أي التالي من الأفعال الخمسة؟', options: ['يذهبان', 'يذهب', 'ذهبا', 'أذهب'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'النحو', explanation: 'الأفعال الخمسة هي: يفعلان، تفعلان، يفعلون، تفعلون، تفعلين.', keywords: ['نحو', 'أفعال خمسة', 'مضارع'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما صيغة المبالغة لاسم الفاعل "كاتب"؟', options: ['كتّاب وكتوب', 'كاتبون', 'مكتوب', 'كتبة'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الصرف', explanation: 'صيغ المبالغة لكاتب: كتّاب على وزن فَعَّال، وكتوب على وزن فَعول.', keywords: ['صرف', 'صيغة مبالغة', 'اسم فاعل'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما المقصود بـ"المصدر الصريح"؟', options: ['ما دل على الحدث مجرداً من الزمن', 'ما دل على الحدث مع الزمن', 'الفعل الماضي في معناه', 'الاسم الدال على الحدث'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الصرف', explanation: 'المصدر الصريح يدل على الحدث مجرداً من الزمن، مثل: قراءة، كتابة، مشي.', keywords: ['صرف', 'مصدر صريح', 'حدث'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما معنى كلمة "وجيز" في اللغة العربية؟', options: ['مختصر وموجز', 'طويل ومفصّل', 'غريب وعجيب', 'صعب وعسير'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'المعجم', explanation: 'وجيز تعني مختصر، من الوجازة أي القِصَر والاختصار.', keywords: ['معجم', 'مفردات', 'وجيز'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما ضد كلمة "البخل"؟', options: ['الكرم', 'الجبن', 'الغضب', 'الكذب'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'المعجم', explanation: 'ضد البخل هو الكرم والجود، والسخاء.', keywords: ['معجم', 'أضداد', 'بخل'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'في علم العروض، ما المقصود بـ"التفعيلة"؟', options: ['الوحدة الموسيقية الأساسية للبيت الشعري', 'نوع من البحور الشعرية', 'القافية في نهاية البيت', 'الوزن الكامل للقصيدة'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'العروض', explanation: 'التفعيلة هي الوحدة الموسيقية الأساسية التي تتكون منها البحور الشعرية مثل: فَعُولن، مَفاعيلن.', keywords: ['عروض', 'تفعيلة', 'شعر'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما المقصود بـ"القافية" في القصيدة الشعرية؟', options: ['الحرف أو الحروف الأخيرة المتشابهة في كل بيت', 'الشطر الأول من البيت', 'الوزن الإيقاعي للقصيدة', 'الموضوع العام للقصيدة'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الشعر', explanation: 'القافية هي الحرف أو المجموعة الحرفية الأخيرة المتكررة في نهاية كل بيت من أبيات القصيدة.', keywords: ['شعر', 'قافية', 'عروض'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما الفرق بين الشعر المرسل والشعر الحر؟', options: ['المرسل له وزن بلا قافية، والحر لا يلتزم بوزن أو قافية محدد', 'لا فرق بينهما', 'الحر له قافية بلا وزن', 'المرسل بلا وزن ولا قافية'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الشعر', explanation: 'الشعر المرسل له وزن دون قافية، والشعر الحر له وزن ولكن بدون التزام قافية ثابتة.', keywords: ['شعر', 'شعر مرسل', 'شعر حر'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما مفهوم "الأسلوب الخبري"؟', options: ['ما يحتمل الصدق والكذب من الكلام', 'ما لا يحتمل الصدق والكذب', 'صيغة الأمر والنهي', 'أسلوب السؤال والاستفهام'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'البلاغة', explanation: 'الأسلوب الخبري هو الكلام الذي يحتمل الصدق والكذب في ذاته، وهو مقابل الإنشاء.', keywords: ['بلاغة', 'خبر', 'إنشاء'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'أين يقع "المبتدأ" في الجملة الاسمية؟', options: ['في أول الجملة عادةً', 'في آخر الجملة', 'في وسط الجملة', 'لا مكان محدد له'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'النحو', explanation: 'المبتدأ يقع في أول الجملة الاسمية، وهو الاسم المرفوع الذي يُخبر عنه بالخبر.', keywords: ['نحو', 'مبتدأ', 'جملة اسمية'] },
  { category: 'general', subcategory: 'اللغة العربية', text: 'ما الفعل المناسب لتعدية "الجسر" في المثال: "--- المهندسون الجسرَ"؟', options: ['شيَّدَ / بنى', 'كسر / هدم', 'استعمل / ركب', 'حفر / أنشأ'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'المعجم', explanation: 'الأفعال المناسبة لبناء الجسر هي: شيَّد، بنى، أقام، أنشأ.', keywords: ['معجم', 'توظيف الكلمات', 'أفعال'] },
];

// ===== أسئلة التربية الإسلامية =====
const islamicStudiesQuestions: QuestionData[] = [
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما عدد أركان الإسلام؟', options: ['خمسة', 'ستة', 'أربعة', 'سبعة'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'العقيدة', explanation: 'أركان الإسلام خمسة: الشهادتان، الصلاة، الزكاة، الصوم، الحج.', keywords: ['إسلام', 'أركان', 'عقيدة'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'كم عدد أركان الإيمان؟', options: ['ستة', 'خمسة', 'سبعة', 'أربعة'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'العقيدة', explanation: 'أركان الإيمان ستة: الإيمان بالله، وملائكته، وكتبه، ورسله، واليوم الآخر، والقدر خيره وشره.', keywords: ['إيمان', 'أركان', 'عقيدة'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما اسم زوجة النبي ﷺ التي تُلقَّب بـ"أم المساكين"؟', options: ['خديجة بنت خويلد', 'عائشة بنت أبي بكر', 'زينب بنت خزيمة', 'حفصة بنت عمر'], correctOptionIndex: 2, difficulty: 'intermediate', topic: 'السيرة النبوية', explanation: 'زينب بنت خزيمة رضي الله عنها هي التي لُقِّبت بأم المساكين لكثرة إطعامها للفقراء.', keywords: ['سيرة نبوية', 'أمهات المؤمنين', 'زينب'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'في أي سنة هجرية كانت غزوة بدر الكبرى؟', options: ['السنة الثانية', 'السنة الثالثة', 'السنة الأولى', 'السنة الرابعة'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'السيرة النبوية', explanation: 'غزوة بدر الكبرى كانت في السنة الثانية من الهجرة النبوية، في شهر رمضان.', keywords: ['سيرة', 'بدر', 'غزوات'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما معنى كلمة "التوحيد" في الاصطلاح الشرعي؟', options: ['إفراد الله بالعبادة', 'الإيمان بوجود الله', 'الإيمان بالملائكة', 'الإيمان بالكتب السماوية'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'العقيدة', explanation: 'التوحيد في الاصطلاح الشرعي هو إفراد الله بما يختص به من الربوبية والألوهية والأسماء والصفات.', keywords: ['عقيدة', 'توحيد', 'إفراد'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما حكم الصلاة في الإسلام؟', options: ['فرض عين', 'فرض كفاية', 'سنة مؤكدة', 'مستحب'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الفقه', explanation: 'الصلاة فرض عين على كل مسلم مكلف، وهي ركن من أركان الإسلام.', keywords: ['فقه', 'صلاة', 'فرض'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما الذي يُبطل الصيام؟', options: ['الأكل والشرب عمداً', 'النوم نهاراً', 'رؤية الطعام', 'شم رائحة الطعام'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الفقه', explanation: 'من مبطلات الصيام: الأكل والشرب عمداً، والجماع، والردة، والحيض والنفاس للمرأة.', keywords: ['فقه', 'صيام', 'مبطلات'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما نصاب زكاة الذهب؟', options: ['85 جراماً', '70 جراماً', '100 جرام', '50 جراماً'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الفقه', explanation: 'نصاب الذهب هو عشرون مثقالاً أي ما يعادل 85 جراماً تقريباً.', keywords: ['فقه', 'زكاة', 'نصاب ذهب'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'في أي شهر يكون الحج؟', options: ['ذو الحجة', 'رمضان', 'ذو القعدة', 'المحرم'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الفقه', explanation: 'الحج يكون في شهر ذي الحجة، وأشهر الحج هي: شوال وذو القعدة وعشر من ذي الحجة.', keywords: ['فقه', 'حج', 'ذو الحجة'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما المقصود بـ"السنة النبوية"؟', options: ['قول النبي ﷺ وفعله وتقريره', 'الأحاديث المكتوبة فقط', 'القرآن الكريم', 'كتب الفقه الإسلامي'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'علوم الحديث', explanation: 'السنة النبوية هي ما صدر عن النبي ﷺ من أقوال وأفعال وتقريرات وصفات خَلقية وخُلقية.', keywords: ['حديث', 'سنة نبوية', 'تعريف'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما أنواع النية في الأعمال؟', options: ['خالصة لله، ومشوبة بالرياء', 'صادقة وكاذبة', 'واجبة ومستحبة', 'حاضرة وغائبة'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الأخلاق', explanation: 'النية إما أن تكون خالصة لله وهي المقبولة، أو مشوبة بالرياء وهي مذمومة قد تُفسد العمل.', keywords: ['أخلاق', 'نية', 'إخلاص'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما الفرق بين الحديث الصحيح والحسن؟', options: ['الحسن أدنى درجةً في الضبط من الصحيح', 'الحسن أعلى درجة من الصحيح', 'لا فرق بينهما', 'الصحيح يُروى بسند متواتر فقط'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'علوم الحديث', explanation: 'الحديث الحسن يشترط فيه ما يشترط في الصحيح إلا أن رواته يكونون أدنى في الضبط والحفظ.', keywords: ['حديث', 'حسن', 'صحيح'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما أول ما يُحاسَب عليه العبد يوم القيامة؟', options: ['الصلاة', 'الزكاة', 'الصوم', 'الحج'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'العقيدة', explanation: 'روى النبي ﷺ أن أول ما يُحاسَب عليه العبد يوم القيامة من عمله الصلاة.', keywords: ['عقيدة', 'حساب', 'صلاة'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما المقصود بـ"الشرك الأكبر"؟', options: ['صرف نوع من أنواع العبادة لغير الله', 'ارتكاب الكبائر', 'عصيان الوالدين', 'إهمال الفرائض'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'العقيدة', explanation: 'الشرك الأكبر هو صرف عبادة ما لغير الله كالذبح والنذر والدعاء والاستغاثة لغير الله.', keywords: ['عقيدة', 'شرك', 'توحيد'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'من هو أبو الأنبياء؟', options: ['إبراهيم عليه السلام', 'نوح عليه السلام', 'آدم عليه السلام', 'موسى عليه السلام'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'القصص القرآني', explanation: 'إبراهيم عليه السلام هو أبو الأنبياء، وهو جد النبي ﷺ.', keywords: ['أنبياء', 'إبراهيم', 'قصص قرآني'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما أسماء الله الحسنى؟', options: ['تسعة وتسعون اسماً', 'مئة اسم', 'مئة وعشرون اسماً', 'غير محددة العدد'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'العقيدة', explanation: 'الله له أسماء حسنى وردت في السنة النبوية تسعة وتسعون اسماً، من أحصاها دخل الجنة.', keywords: ['عقيدة', 'أسماء الله', 'حسنى'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما المقصود بـ"فقه الأولويات"؟', options: ['تقديم الأهم على المهم في الأعمال الشرعية', 'الاهتمام بالأمور الأساسية فقط', 'إهمال الأمور الثانوية', 'كلها صحيحة'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'الفقه', explanation: 'فقه الأولويات هو معرفة ترتيب الأعمال والأحكام الشرعية من حيث الأهمية والأثر.', keywords: ['فقه', 'أولويات', 'ترتيب'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما المقصود بـ"المعجزة"؟', options: ['أمر خارق للعادة يُجريه الله على يد نبي تحدياً للمكذِّبين', 'كرامة يُعطاها الولي الصالح', 'حلم صادق يراه الإنسان', 'استجابة الدعاء'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'العقيدة', explanation: 'المعجزة هي أمر خارق للعادة يُظهره الله على يد أنبيائه دليلاً على صدق نبوتهم.', keywords: ['عقيدة', 'معجزة', 'أنبياء'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما الحكمة من فريضة الحج؟', options: ['توحيد المسلمين وتذكيرهم بيوم القيامة', 'السياحة الدينية فقط', 'الاطلاع على البلدان المختلفة', 'لا حكمة محددة'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الفقه', explanation: 'للحج حِكَم جليلة منها: توحيد المسلمين، والتذكير بيوم الحشر، وتعزيز الوحدة الإسلامية.', keywords: ['فقه', 'حج', 'حكمة'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما أهمية بر الوالدين في الإسلام؟', options: ['من أعظم الواجبات وفضله عظيم', 'مستحب وليس واجباً', 'واجب على الصغار فقط', 'يختلف بحسب الحال'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الأخلاق', explanation: 'بر الوالدين من أعظم الواجبات وقرنه الله بعبادته في القرآن الكريم.', keywords: ['أخلاق', 'والدين', 'بر'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما حكم صلاة الجمعة؟', options: ['فرض عين على الرجال المستطيعين', 'فرض كفاية', 'سنة مؤكدة', 'مستحب'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الفقه', explanation: 'صلاة الجمعة فرض عين على كل مسلم ذكر مكلف مقيم مستطيع.', keywords: ['فقه', 'جمعة', 'صلاة'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما المحرَّم من الأطعمة في الإسلام؟', options: ['الخنزير والميتة والدم والخمر', 'اللحوم عموماً', 'الخضروات المعينة', 'لا يوجد محرمات'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الفقه', explanation: 'المحرمات من الأطعمة: الميتة، الدم المسفوح، لحم الخنزير، وما أُهِلَّ لغير الله به.', keywords: ['فقه', 'محرمات', 'أطعمة'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما الفرق بين الزكاة والصدقة؟', options: ['الزكاة فرض محددة النسبة، والصدقة تطوع', 'الصدقة أكثر ثواباً من الزكاة', 'لا فرق بينهما', 'الزكاة للفقراء فقط والصدقة للجميع'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الفقه', explanation: 'الزكاة ركن من أركان الإسلام، محددة النسبة والشروط، أما الصدقة فهي تطوع يتفاوت قدرها.', keywords: ['فقه', 'زكاة', 'صدقة'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما شروط الحج؟', options: ['الإسلام والبلوغ والعقل والاستطاعة', 'الإسلام فقط', 'البلوغ والمال فقط', 'العقل والمال والصحة'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الفقه', explanation: 'شروط وجوب الحج: الإسلام، البلوغ، العقل، الحرية، الاستطاعة.', keywords: ['فقه', 'حج', 'شروط'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما أعظم آية في القرآن الكريم؟', options: ['آية الكرسي', 'الفاتحة', 'آية الدَّين', 'سورة الإخلاص'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'علوم القرآن', explanation: 'آية الكرسي (البقرة:255) هي أعظم آية في القرآن الكريم كما ورد في الحديث النبوي الشريف.', keywords: ['قرآن', 'آية الكرسي', 'فضل'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما المقصود بـ"الإجماع" في الفقه الإسلامي؟', options: ['اتفاق علماء الأمة في عصر ما على حكم شرعي', 'رأي فقيه واحد مشهور', 'الرأي الأكثر في المذاهب', 'اتفاق الحكام المسلمين'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'أصول الفقه', explanation: 'الإجماع في الاصطلاح: اتفاق علماء الأمة الإسلامية في عصر من العصور على حكم شرعي.', keywords: ['أصول فقه', 'إجماع', 'تعريف'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'كم سورة في القرآن الكريم؟', options: ['114', '100', '120', '110'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'علوم القرآن', explanation: 'القرآن الكريم يتكون من 114 سورة، أولها الفاتحة وآخرها الناس.', keywords: ['قرآن', 'سور', 'عدد'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما الصلوات الخمس وأوقاتها؟', options: ['الفجر والظهر والعصر والمغرب والعشاء', 'الفجر والضحى والظهر والعصر والمغرب', 'الليل والفجر والظهر والعصر والمغرب', 'الفجر والظهر والعصر والمغرب والوتر'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الفقه', explanation: 'الصلوات الخمس هي: الفجر (ركعتان)، الظهر (أربع)، العصر (أربع)، المغرب (ثلاث)، العشاء (أربع).', keywords: ['فقه', 'صلاة', 'أوقات'] },
  { category: 'general', subcategory: 'التربية الإسلامية', text: 'ما المقصود بـ"القياس" في أصول الفقه؟', options: ['إلحاق مسألة غير منصوص عليها بمسألة منصوص عليها لاشتراكهما في العلة', 'الاجتهاد الفردي للعالم', 'استنباط الحكم من القرآن فقط', 'تقليد المذاهب الأربعة'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'أصول الفقه', explanation: 'القياس: إلحاق فرع بأصل في الحكم لاشتراكهما في علة الحكم، وهو أحد مصادر التشريع الإسلامي.', keywords: ['أصول فقه', 'قياس', 'اجتهاد'] },
];

// ===== أسئلة الرياضيات =====
const mathQuestions: QuestionData[] = [
  { category: 'general', subcategory: 'الرياضيات', text: 'ما ناتج: (3 + 5) × 2 - 4 ÷ 2؟', options: ['14', '10', '16', '12'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'العمليات الحسابية', explanation: 'حسب قاعدة الأولويات: (3+5)=8، ثم 8×2=16، ثم 4÷2=2، ثم 16-2=14.', keywords: ['حساب', 'عمليات', 'أولويات'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما قيمة x في المعادلة: 2x + 5 = 13؟', options: ['4', '3', '5', '6'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الجبر', explanation: '2x = 13-5 = 8، إذن x = 4.', keywords: ['جبر', 'معادلة', 'مجهول'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما مساحة المثلث إذا كانت قاعدته 8 سم وارتفاعه 5 سم؟', options: ['20 سم²', '40 سم²', '13 سم²', '80 سم²'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الهندسة', explanation: 'مساحة المثلث = (القاعدة × الارتفاع) ÷ 2 = (8×5)÷2 = 20 سم².', keywords: ['هندسة', 'مثلث', 'مساحة'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما محيط الدائرة التي نصف قطرها 7 سم؟ (π ≈ 22/7)', options: ['44 سم', '154 سم', '22 سم', '88 سم'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الهندسة', explanation: 'محيط الدائرة = 2πr = 2 × (22/7) × 7 = 44 سم.', keywords: ['هندسة', 'دائرة', 'محيط'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما قيمة 5² + 4²؟', options: ['41', '81', '29', '45'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الأعداد', explanation: '5² = 25، و4² = 16، إذن 25 + 16 = 41.', keywords: ['أعداد', 'أسس', 'قوى'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'إذا كان sin(30°) = 1/2، فما قيمة cos(60°)؟', options: ['1/2', '√3/2', '1', '0'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'المثلثات', explanation: 'cos(60°) = sin(30°) = 1/2 لأن (90°-60°=30°).', keywords: ['مثلثات', 'جيب', 'جيب تمام'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما قيمة log₁₀(100)؟', options: ['2', '10', '100', '1'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'اللوغاريتمات', explanation: 'log₁₀(100) = log₁₀(10²) = 2.', keywords: ['لوغاريتم', 'أسس', 'حساب'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما التشكيلة C(5,2)؟', options: ['10', '20', '15', '5'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التوافيق', explanation: 'C(5,2) = 5! ÷ (2! × 3!) = (5×4)/(2×1) = 10.', keywords: ['توافيق', 'تباديل', 'احتمالات'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما مشتقة f(x) = x³؟', options: ['3x²', 'x²', '3x', '2x²'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'التفاضل', explanation: 'بقاعدة مشتقة القوة: d/dx(xⁿ) = nxⁿ⁻¹، فمشتقة x³ = 3x².', keywords: ['تفاضل', 'مشتقة', 'قوة'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما حجم الكرة التي نصف قطرها 3 سم؟ (π ≈ 3.14)', options: ['113.04 سم³', '28.26 سم³', '75.36 سم³', '9 سم³'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الهندسة', explanation: 'حجم الكرة = (4/3)πr³ = (4/3) × 3.14 × 27 = 113.04 سم³.', keywords: ['هندسة', 'كرة', 'حجم'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما حل المجموعة لمعادلة |x - 3| = 5؟', options: ['{8, -2}', '{8, 2}', '{-8, 2}', '{3, 5}'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الجبر', explanation: '|x-3|=5 تعطي: x-3=5 فـ x=8، أو x-3=-5 فـ x=-2.', keywords: ['جبر', 'قيمة مطلقة', 'معادلة'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما الحد العام للمتتالية الحسابية: 2, 5, 8, 11, ...؟', options: ['3n - 1', '3n + 1', '2n + 3', 'n + 3'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'المتتاليات', explanation: 'الحد الأول a₁=2، والأساس d=3. الحد العام = a₁ + (n-1)d = 2 + 3(n-1) = 3n - 1.', keywords: ['متتاليات', 'حسابية', 'حد عام'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما مجموع زوايا المثلث؟', options: ['180°', '360°', '90°', '270°'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الهندسة', explanation: 'مجموع زوايا أي مثلث يساوي 180 درجة.', keywords: ['هندسة', 'مثلث', 'زوايا'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'في المضلع المنتظم ذي 6 أضلاع، ما مجموع زواياه الداخلية؟', options: ['720°', '360°', '540°', '1080°'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الهندسة', explanation: 'مجموع الزوايا الداخلية للمضلع = (n-2) × 180 = (6-2) × 180 = 720°.', keywords: ['هندسة', 'مضلع', 'زوايا داخلية'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'إذا كانت نسبة الذكور إلى الإناث في صف 3:2، وعدد الطلاب 25، كم عدد الذكور؟', options: ['15', '10', '12', '13'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'النسب', explanation: 'المجموع = 3+2 = 5 أجزاء. كل جزء = 25÷5 = 5. الذكور = 3×5 = 15.', keywords: ['نسب', 'تناسب', 'مسائل'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما ناتج (2x + 3)(x - 1)؟', options: ['2x² + x - 3', '2x² - x - 3', '2x² + x + 3', '2x² - x + 3'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الجبر', explanation: '(2x+3)(x-1) = 2x²-2x+3x-3 = 2x²+x-3.', keywords: ['جبر', 'ضرب', 'حدود'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما نوع المثلث الذي قياسات زواياه 60°، 60°، 60°؟', options: ['متساوي الأضلاع', 'متساوي الساقين', 'قائم الزاوية', 'مختلف الأضلاع'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الهندسة', explanation: 'المثلث ذو الزوايا المتساوية 60° هو مثلث متساوي الأضلاع لأن تساوي الزوايا يستلزم تساوي الأضلاع المقابلة.', keywords: ['هندسة', 'مثلث', 'متساوي الأضلاع'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما احتمال ظهور رقم زوجي عند قذف حجر نرد سداسي مرة واحدة؟', options: ['1/2', '1/3', '2/3', '1/6'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الاحتمالات', explanation: 'الأرقام الزوجية على النرد هي: 2، 4، 6. الاحتمال = 3/6 = 1/2.', keywords: ['احتمالات', 'نرد', 'زوجي'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما المتوسط الحسابي للأعداد: 4, 8, 12, 16, 20؟', options: ['12', '10', '14', '16'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الإحصاء', explanation: 'المجموع = 4+8+12+16+20 = 60، والعدد = 5. المتوسط = 60÷5 = 12.', keywords: ['إحصاء', 'متوسط', 'بيانات'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما قيمة x في: √x = 9؟', options: ['81', '3', '9', '18'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الجذور', explanation: 'إذا كانت √x = 9، فإن x = 9² = 81.', keywords: ['جذور', 'تربيع', 'معادلة'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما قانون نظرية فيثاغورس؟', options: ['c² = a² + b²', 'c = a + b', 'c² = a² - b²', 'c² = (a+b)²'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الهندسة', explanation: 'نظرية فيثاغورس: في المثلث القائم الزاوية، مربع الوتر = مجموع مربعي الضلعين الآخرين.', keywords: ['هندسة', 'فيثاغورس', 'مثلث قائم'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما قيمة ∫x dx؟', options: ['x²/2 + C', 'x + C', '2x + C', 'x²+ C'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'التكامل', explanation: '∫x dx = x²/2 + C بتطبيق قاعدة التكامل: ∫xⁿ dx = xⁿ⁺¹/(n+1) + C.', keywords: ['تكامل', 'مشتقات عكسية', 'حساب'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما الفرق بين الأعداد النسبية وغير النسبية؟', options: ['النسبية تكتب كسراً من الأعداد الصحيحة، وغير النسبية لا يمكن ذلك', 'النسبية لها عدد صحيح فقط', 'غير النسبية أكبر من النسبية دائماً', 'لا فرق بينهما'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الأعداد', explanation: 'الأعداد النسبية: تكتب بصورة p/q حيث p وq أعداد صحيحة وq≠0. أما غير النسبية فهي كـ π وe و√2.', keywords: ['أعداد', 'نسبية', 'غير نسبية'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما حل نظام المعادلتين: x+y=5 و x-y=1؟', options: ['x=3, y=2', 'x=2, y=3', 'x=4, y=1', 'x=1, y=4'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الجبر', explanation: 'بجمع المعادلتين: 2x=6 فـ x=3. بتعويضه: 3+y=5 فـ y=2.', keywords: ['جبر', 'نظام معادلات', 'حل'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما ناتج 3⁻²؟', options: ['1/9', '9', '-6', '-1/9'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الأسس', explanation: '3⁻² = 1/3² = 1/9.', keywords: ['أسس', 'سالب', 'كسر'] },
  { category: 'general', subcategory: 'الرياضيات', text: 'ما المنوال للمجموعة: 3, 5, 7, 5, 9, 5, 3؟', options: ['5', '3', '7', '9'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الإحصاء', explanation: 'المنوال هو العدد الأكثر تكراراً. 5 يتكرر 3 مرات وهو الأكثر.', keywords: ['إحصاء', 'منوال', 'تكرار'] },
];

// ===== أسئلة الفيزياء =====
const physicsQuestions: QuestionData[] = [
  { category: 'general', subcategory: 'الفيزياء', text: 'ما وحدة قياس القوة في النظام الدولي؟', options: ['نيوتن (N)', 'جول (J)', 'واط (W)', 'باسكال (Pa)'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الميكانيكا', explanation: 'وحدة القوة في النظام الدولي هي النيوتن (N)، وهي القوة التي تُكسب كتلة 1 كجم تسارعاً قدره 1 م/ث².', keywords: ['فيزياء', 'قوة', 'نيوتن'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما قانون نيوتن الثاني للحركة؟', options: ['F = ma', 'F = m/a', 'F = m+a', 'F = m²a'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الميكانيكا', explanation: 'قانون نيوتن الثاني: القوة = الكتلة × التسارع (F = ma).', keywords: ['ميكانيكا', 'نيوتن', 'قوة'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما وحدة قياس الطاقة في النظام الدولي؟', options: ['جول (J)', 'واط (W)', 'نيوتن (N)', 'باسكال (Pa)'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الطاقة', explanation: 'وحدة الطاقة في النظام الدولي هي الجول (J)، وهي الشغل المبذول بقوة نيوتن واحدة عبر مسافة متر واحد.', keywords: ['طاقة', 'جول', 'وحدات'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما الجهد الكهربائي؟ (تعريف)', options: ['نسبة الطاقة إلى الشحنة (V = W/Q)', 'التيار × المقاومة', 'الشحنة مقسومة على الزمن', 'الطاقة × الشحنة'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الكهرباء', explanation: 'الجهد الكهربائي هو الشغل المبذول لنقل وحدة شحنة بين نقطتين (V = W/Q).', keywords: ['كهرباء', 'جهد', 'تعريف'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما قانون أوم؟', options: ['V = IR', 'V = I/R', 'V = I+R', 'V = I²R'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الكهرباء', explanation: 'قانون أوم: الجهد = التيار × المقاومة (V = IR).', keywords: ['كهرباء', 'أوم', 'قانون'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما سرعة الضوء في الفراغ تقريباً؟', options: ['3 × 10⁸ م/ث', '3 × 10⁶ م/ث', '3 × 10¹⁰ م/ث', '3 × 10⁵ م/ث'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الضوء', explanation: 'سرعة الضوء في الفراغ تبلغ تقريباً 3 × 10⁸ م/ث أو 300,000 كم/ث.', keywords: ['ضوء', 'سرعة', 'فراغ'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما الفرق بين الصوت والضوء من حيث الوسط الناقل؟', options: ['الصوت يحتاج وسطاً مادياً، والضوء لا يحتاج', 'كلاهما يحتاج وسطاً مادياً', 'كلاهما لا يحتاج وسطاً مادياً', 'الضوء يحتاج وسطاً مادياً، والصوت لا يحتاج'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الأمواج', explanation: 'الصوت موجة ميكانيكية تحتاج وسطاً مادياً للانتقال، أما الضوء فهو موجة كهرومغناطيسية تنتقل في الفراغ.', keywords: ['صوت', 'ضوء', 'وسط ناقل'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما الطاقة الحركية لجسم كتلته 2 كجم وسرعته 3 م/ث؟', options: ['9 جول', '6 جول', '12 جول', '18 جول'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الطاقة', explanation: 'طاقة حركية = ½mv² = ½ × 2 × 3² = ½ × 2 × 9 = 9 جول.', keywords: ['طاقة حركية', 'حساب', 'ميكانيكا'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما قانون الجاذبية العالمية (جاذبية نيوتن)؟', options: ['F = Gm₁m₂/r²', 'F = m₁m₂/r', 'F = Gm₁m₂r', 'F = G(m₁+m₂)/r²'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الجاذبية', explanation: 'قانون الجاذبية لنيوتن: القوة = G × (ضرب الكتلتين)/(مربع المسافة بينهما).', keywords: ['جاذبية', 'نيوتن', 'قانون'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما وحدة الضغط في النظام الدولي؟', options: ['باسكال (Pa)', 'نيوتن (N)', 'جول (J)', 'واط (W)'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الموائع', explanation: 'وحدة الضغط هي الباسكال (Pa) = نيوتن/متر².', keywords: ['ضغط', 'باسكال', 'وحدات'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما الظاهرة التي تفسر لماذا السماء زرقاء؟', options: ['تبعثر ريلي', 'الانعكاس الكلي', 'الانكسار', 'الحيود'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'الضوء', explanation: 'تبعثر ريلي: يتبعثر الضوء من الجزيئات، والضوء الأزرق ذو الطول الموجي القصير يتبعثر أكثر من غيره.', keywords: ['ضوء', 'تبعثر', 'سماء'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما الفرق بين الحرارة ودرجة الحرارة؟', options: ['الحرارة طاقة منتقلة، ودرجة الحرارة مقياس السخونة', 'لا فرق بينهما', 'درجة الحرارة طاقة ودرجة الحرارة متوسط حركة', 'الحرارة للمواد الصلبة فقط'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الحرارة', explanation: 'الحرارة هي الطاقة المنتقلة من جسم لآخر بسبب فرق درجات الحرارة، أما درجة الحرارة فهي مقياس السخونة.', keywords: ['حرارة', 'درجة حرارة', 'فرق'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'في التيار المتردد، ما التردد القياسي في السعودية؟', options: ['60 هرتز', '50 هرتز', '100 هرتز', '220 هرتز'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الكهرباء', explanation: 'تردد التيار المتردد في المملكة العربية السعودية هو 60 هرتز، والجهد الكهربائي 120 فولت.', keywords: ['كهرباء', 'تردد', 'تيار متردد'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما المقصود بـ"الرنين"؟', options: ['اهتزاز جسم بتردده الطبيعي عند تعرضه لقوة دورية بنفس التردد', 'تداخل موجتين', 'انعكاس الصوت', 'امتصاص الطاقة'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الأمواج', explanation: 'الرنين ظاهرة تحدث حين يتوافق تردد القوة المحرِّكة مع التردد الطبيعي للجسم فيزداد اتساع الاهتزاز.', keywords: ['رنين', 'موجات', 'اهتزاز'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما قيمة تسارع الجاذبية الأرضية تقريباً؟', options: ['9.8 م/ث²', '10 م/ث²', '9 م/ث²', '8.9 م/ث²'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الجاذبية', explanation: 'قيمة تسارع الجاذبية الأرضية g ≈ 9.8 م/ث² (يُقرَّب أحياناً لـ 10 م/ث²).', keywords: ['جاذبية', 'تسارع', 'أرض'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما مبدأ عدم اليقين لهايزنبرغ؟', options: ['لا يمكن تحديد موضع الجسيم وكميته الحركية بدقة في آنٍ واحد', 'لا يمكن قياس الجسيمات الدقيقة', 'الطاقة مكممة دائماً', 'الضوء له طبيعة مزدوجة'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'الفيزياء الحديثة', explanation: 'مبدأ هايزنبرغ: Δx·Δp ≥ ℏ/2 أي أن دقة قياس الموضع تتعارض مع دقة قياس كمية الحركة.', keywords: ['فيزياء حديثة', 'هايزنبرغ', 'كم'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما الفرق بين الموجات الطولية والعرضية؟', options: ['الطولية تهتز في اتجاه الانتشار، والعرضية عمودياً عليه', 'لا فرق بينهما في الاهتزاز', 'العرضية أسرع من الطولية', 'الطولية تحتاج وسطاً أكثر'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الأمواج', explanation: 'الموجات الطولية: الاهتزاز في اتجاه انتشار الموجة مثل الصوت. العرضية: الاهتزاز عمودي على الانتشار مثل الضوء.', keywords: ['موجات', 'طولية', 'عرضية'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما وحدة التيار الكهربائي؟', options: ['أمبير (A)', 'فولت (V)', 'واط (W)', 'أوم (Ω)'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الكهرباء', explanation: 'وحدة قياس التيار الكهربائي هي الأمبير (A)، ويُعرَّف بأنه مرور شحنة كولوم واحدة خلال ثانية.', keywords: ['كهرباء', 'تيار', 'أمبير'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما مبدأ أرخميدس؟', options: ['الجسم الغاطس في سائل يتأثر بقوة طفو تساوي وزن السائل المزاح', 'الضغط يتوزع بالتساوي في السائل', 'الضغط يزداد مع العمق', 'السوائل ترتفع في الأنابيب الشعرية'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الموائع', explanation: 'مبدأ أرخميدس: قوة الطفو = وزن السائل المزاح = ρ × V × g.', keywords: ['موائع', 'أرخميدس', 'طفو'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما المقصود بـ"مجال الجاذبية"؟', options: ['القوة بالنسبة لوحدة الكتلة في نقطة ما', 'التسارع الأفقي', 'مجموع قوى الجاذبية', 'وزن الجسم'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'الجاذبية', explanation: 'مجال الجاذبية = g = F/m (القوة ÷ الكتلة)، ويُقاس بالنيوتن/كجم أو م/ث².', keywords: ['جاذبية', 'مجال', 'تعريف'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما المقصود بالناقلية الكهربائية؟', options: ['مقدرة المادة على توصيل التيار الكهربائي', 'مقاومة المادة للتيار', 'الشحنة المخزنة', 'الطاقة المبددة'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الكهرباء', explanation: 'الناقلية الكهربائية هي مدى سهولة مرور التيار في المادة، وهي عكس المقاومة.', keywords: ['كهرباء', 'ناقلية', 'مقاومة'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما الطاقة الكامنة الجذبية لجسم كتلته 5 كجم على ارتفاع 10م؟ (g=10 م/ث²)', options: ['500 جول', '50 جول', '5000 جول', '100 جول'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الطاقة', explanation: 'طاقة كامنة جذبية = mgh = 5 × 10 × 10 = 500 جول.', keywords: ['طاقة كامنة', 'جاذبية', 'ميكانيكا'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما ظاهرة التحريض الكهرومغناطيسي؟', options: ['توليد تيار كهربائي بتغيير المجال المغناطيسي', 'توليد مجال مغناطيسي بالتيار', 'الجذب المغناطيسي', 'تشتيت الضوء'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الكهرومغناطيسية', explanation: 'التحريض الكهرومغناطيسي: ينشأ قوة دافعة كهرومغناطيسية وتيار عند تغيير الفيض المغناطيسي (فاراداي).', keywords: ['كهرومغناطيسية', 'تحريض', 'فاراداي'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما المقصود بـ"التردد" للموجة؟', options: ['عدد الدورات الكاملة في الثانية الواحدة', 'المسافة بين قمتين متتاليتين', 'سرعة انتشار الموجة', 'ارتفاع الموجة'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الأمواج', explanation: 'التردد هو عدد الاهتزازات أو الدورات الكاملة التي تحدث في الثانية الواحدة، ويُقاس بالهرتز (Hz).', keywords: ['موجات', 'تردد', 'هرتز'] },
  { category: 'general', subcategory: 'الفيزياء', text: 'ما علاقة السرعة والطول الموجي والتردد؟', options: ['v = fλ', 'v = f/λ', 'v = λ/f', 'v = f+λ'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الأمواج', explanation: 'السرعة = التردد × الطول الموجي (v = fλ).', keywords: ['موجات', 'سرعة', 'علاقة'] },
];

// ===== أسئلة الكيمياء =====
const chemistryQuestions: QuestionData[] = [
  { category: 'general', subcategory: 'الكيمياء', text: 'ما العدد الذري للكربون؟', options: ['6', '12', '8', '4'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الجدول الدوري', explanation: 'العدد الذري للكربون هو 6، أي أن نواته تحتوي على 6 بروتونات.', keywords: ['كيمياء', 'كربون', 'عدد ذري'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما صيغة الماء الكيميائية؟', options: ['H₂O', 'HO₂', 'H₂O₂', 'OH'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'المركبات', explanation: 'صيغة الماء الكيميائية H₂O: ذرتا هيدروجين وذرة أكسجين.', keywords: ['كيمياء', 'ماء', 'مركبات'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما نوع التفاعل: CH₄ + 2O₂ → CO₂ + 2H₂O؟', options: ['تفاعل احتراق', 'تفاعل تحلل', 'تفاعل تعادل', 'تفاعل إحلال'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التفاعلات الكيميائية', explanation: 'احتراق الميثان CH₄ مع الأكسجين هو تفاعل احتراق ينتج ثاني أكسيد الكربون والماء.', keywords: ['احتراق', 'تفاعل', 'ميثان'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما تعريف الحامض حسب برونستد-لاوري؟', options: ['المادة التي تعطي بروتوناً (H⁺)', 'المادة التي تعطي إلكتروناً', 'المادة ذات pH أقل من 7', 'المادة التي تُحلل الماء'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الأحماض والقواعد', explanation: 'حسب برونستد-لاوري: الحامض مانح البروتون (H⁺) والقاعدة متقبلة البروتون.', keywords: ['أحماض', 'قواعد', 'برونستد'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما التركيب الإلكتروني لعنصر الصوديوم (Na) العدد الذري 11؟', options: ['2, 8, 1', '2, 8, 2', '2, 9', '2, 8, 3'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التركيب الذري', explanation: 'الصوديوم (Z=11): التركيب الإلكتروني 2, 8, 1 (الطبقة الأولى 2، الثانية 8، الثالثة 1).', keywords: ['تركيب ذري', 'صوديوم', 'إلكترونات'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما الفرق بين التفاعل الطارد للحرارة والماص للحرارة؟', options: ['الطارد يُفرز حرارة والماص يمتصها', 'الطارد أسرع من الماص', 'الماص أكثر استقراراً', 'لا فرق حقيقي'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الديناميكا الحرارية', explanation: 'التفاعل الطارد للحرارة (ΔH<0): يُطلق حرارة للمحيط. الماص للحرارة (ΔH>0): يمتص حرارة من المحيط.', keywords: ['ديناميكا حرارية', 'حرارة', 'تفاعل'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما وحدة قياس كتلة المولات؟', options: ['جرام/مول', 'جرام/لتر', 'مول/لتر', 'جرام فقط'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الستويكيومترية', explanation: 'الكتلة المولية تُقاس بـ جرام/مول (g/mol)، وتساوي عدد المول من المادة في الجرامات.', keywords: ['مول', 'كتلة مولية', 'وحدات'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما المقصود بالرابطة التساهمية؟', options: ['مشاركة الإلكترونات بين ذرتين', 'نقل الإلكترونات من ذرة لأخرى', 'جذب أيونات موجبة لسالبة', 'جذب ذرات في الفلزات'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الروابط الكيميائية', explanation: 'الرابطة التساهمية: تشترك ذرتان أو أكثر في زوج أو أزواج من الإلكترونات لتحقيق الاستقرار.', keywords: ['روابط', 'تساهمية', 'إلكترونات'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما الفلز الذي يبقى سائلاً عند درجة حرارة الغرفة؟', options: ['الزئبق (Hg)', 'الحديد (Fe)', 'الذهب (Au)', 'الصوديوم (Na)'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'خواص المواد', explanation: 'الزئبق هو الفلز الوحيد الذي يكون سائلاً في ظروف الضغط الجوي ودرجة حرارة الغرفة.', keywords: ['فلزات', 'زئبق', 'سائل'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما قانون حفظ الكتلة في التفاعلات الكيميائية؟', options: ['مجموع كتل المتفاعلات = مجموع كتل النواتج', 'الكتلة تتحول إلى طاقة', 'الكتلة قد تزداد أو تقل', 'الكتلة ثابتة فقط في التفاعلات الطاردة'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'التفاعلات الكيميائية', explanation: 'قانون لافوازييه: الكتلة لا تُستحدث ولا تُفنى في التفاعلات الكيميائية.', keywords: ['حفظ كتلة', 'لافوازييه', 'قانون'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما الرقم الهيدروجيني (pH) للمحاليل المتعادلة؟', options: ['7', '0', '14', '1'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الأحماض والقواعد', explanation: 'المحلول المتعادل له pH = 7، الحمضي له pH < 7، والقاعدي له pH > 7.', keywords: ['pH', 'تعادل', 'أحماض'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما الفرق بين الأيزوتوبات؟', options: ['نفس العدد الذري وعدد كتلة مختلف', 'نفس العدد الكتلي وعدد ذري مختلف', 'نفس عدد الإلكترونات ومختلفة في البروتونات', 'مختلفة في كل شيء'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التركيب الذري', explanation: 'الأيزوتوبات: ذرات نفس العنصر لها نفس العدد الذري (البروتونات) لكن أعداد الكتلة مختلفة (نيوترونات مختلفة).', keywords: ['أيزوتوبات', 'نيوترونات', 'تركيب ذري'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما قانون بويل للغازات؟', options: ['عند ثبات درجة الحرارة: P₁V₁ = P₂V₂', 'عند ثبات الضغط: V₁/T₁ = V₂/T₂', 'PV = nRT', 'P/T = ثابت'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'قوانين الغازات', explanation: 'قانون بويل: عند درجة حرارة ثابتة، ضرب الضغط في الحجم ثابت (P₁V₁=P₂V₂).', keywords: ['غازات', 'بويل', 'قانون'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما المقصود بالتأكسد في الكيمياء؟', options: ['فقدان الإلكترونات', 'اكتساب الإلكترونات', 'اكتساب الأكسجين فقط', 'فقدان الهيدروجين فقط'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التفاعلات الأكسدة والاختزال', explanation: 'التأكسد هو فقدان الإلكترونات (أو اكتساب الأكسجين أو فقدان الهيدروجين). الاختزال عكسه.', keywords: ['أكسدة', 'اختزال', 'إلكترونات'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما عدد إلكترونات الطبقة الخارجية لعنصر الكلور (Z=17)؟', options: ['7', '17', '8', '2'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التركيب الذري', explanation: 'الكلور (Z=17): التوزيع الإلكتروني 2, 8, 7. إذن لديه 7 إلكترونات في الطبقة الخارجية.', keywords: ['كلور', 'إلكترونات', 'طبقة خارجية'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما المقصود بـ"الاتزان الكيميائي"؟', options: ['الحالة التي تتساوى فيها سرعتا التفاعل الأمامي والعكسي', 'توقف التفاعل الكيميائي', 'تحويل المتفاعلات إلى نواتج بالكامل', 'ذوبان المادة في المحلول'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'الاتزان الكيميائي', explanation: 'الاتزان الكيميائي يتحقق حين يتساوى معدل التفاعل الأمامي مع معدل التفاعل العكسي.', keywords: ['اتزان كيميائي', 'سرعة تفاعل', 'ديناميكي'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما الاسم الكيميائي لـ NaOH؟', options: ['هيدروكسيد الصوديوم', 'كلوريد الصوديوم', 'كبريتات الصوديوم', 'كربونات الصوديوم'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'المركبات', explanation: 'NaOH هو هيدروكسيد الصوديوم، وهو قاعدة قوية تُستخدم في الصناعة.', keywords: ['مركبات', 'هيدروكسيد صوديوم', 'NaOH'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما خاصية المواد الأمفوتيرية؟', options: ['تتفاعل كأحماض وكقواعد معاً', 'تتفاعل كأحماض فقط', 'تتفاعل كقواعد فقط', 'لا تتفاعل مع الأحماض ولا القواعد'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'الأحماض والقواعد', explanation: 'المواد الأمفوتيرية مثل الماء والألومينيوم يمكنها التفاعل سواء كأحماض أو كقواعد.', keywords: ['أمفوتيري', 'أحماض', 'قواعد'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما المقصود بـ"عامل الحفز"؟', options: ['مادة تُسرِّع التفاعل دون أن تُستهلك', 'مادة تُبطئ التفاعل', 'مادة تدخل في ناتج التفاعل', 'مادة تمتص الحرارة'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الحركية الكيميائية', explanation: 'العامل الحفاز (المحفز) يُسرِّع التفاعل الكيميائي بخفض طاقة التنشيط دون أن يُستهلك في التفاعل.', keywords: ['محفز', 'تسريع', 'تفاعل'] },
  { category: 'general', subcategory: 'الكيمياء', text: 'ما الوزن المولي لثاني أكسيد الكربون CO₂؟', options: ['44 جرام/مول', '28 جرام/مول', '32 جرام/مول', '22 جرام/مول'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الستويكيومترية', explanation: 'CO₂: C=12, O=16×2=32. إذن الوزن المولي = 12+32 = 44 جرام/مول.', keywords: ['وزن مولي', 'CO2', 'حساب'] },
];

// ===== أسئلة الأحياء =====
const biologyQuestions: QuestionData[] = [
  { category: 'general', subcategory: 'الأحياء', text: 'ما وحدة البناء الأساسية للكائنات الحية؟', options: ['الخلية', 'الذرة', 'الجزيء', 'النسيج'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الخلية', explanation: 'الخلية هي الوحدة البنائية والوظيفية الأساسية للكائنات الحية.', keywords: ['خلية', 'بناء', 'أحياء'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما وظيفة الكلوروفيل في النباتات؟', options: ['امتصاص الضوء لتحويله إلى طاقة كيميائية', 'النقل الغذائي', 'التنفس الخلوي', 'تخزين الماء'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'البناء الضوئي', explanation: 'الكلوروفيل هو الصبغة الخضراء في النبات التي تمتص الضوء وتحوله إلى طاقة كيميائية في عملية البناء الضوئي.', keywords: ['كلوروفيل', 'بناء ضوئي', 'نبات'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما الفرق الرئيسي بين الخلية النباتية والحيوانية؟', options: ['النباتية لها جدار خلوي وبلاستيدات خضراء', 'الحيوانية أكبر حجماً', 'النباتية لا تحتوي على نواة', 'الحيوانية لها جدار خلوي صلب'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الخلية', explanation: 'الخلية النباتية تتميز بوجود جدار خلوي سليلوزي وبلاستيدات خضراء وفجوة عصارية كبيرة.', keywords: ['خلية نباتية', 'خلية حيوانية', 'فرق'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما عملية البناء الضوئي وأين تتم؟', options: ['تحويل الضوء إلى طاقة كيميائية في البلاستيدات الخضراء', 'تفكيك الجلوكوز في الميتوكوندريا', 'تصنيع البروتين في الريبوسومات', 'نقل الجينات من نواة لأخرى'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'البناء الضوئي', explanation: 'البناء الضوئي يتم في البلاستيدات الخضراء: CO₂+H₂O+ضوء → C₆H₁₂O₆+O₂', keywords: ['بناء ضوئي', 'بلاستيدات', 'كلوروبلاست'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما الكروموسومات وما وظيفتها؟', options: ['خيوط تحمل الجينات الوراثية في النواة', 'أغشية تحيط بالنواة', 'أجسام تُنتج الطاقة', 'مواد تُحلل البروتين'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الوراثة', explanation: 'الكروموسومات خيوط من DNA وبروتين توجد في النواة وتحمل الجينات المسؤولة عن الصفات الوراثية.', keywords: ['كروموسومات', 'جينات', 'وراثة'] },
  { category: 'general', subcategory: 'الأحياء', text: 'كم عدد كروموسومات الإنسان في الخلايا الجسمية؟', options: ['46', '23', '48', '92'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الوراثة', explanation: 'الخلية الجسمية الإنسانية تحتوي على 46 كروموسوم (23 زوجاً)، بينما الخلايا الجنسية تحتوي على 23 كروموسوم.', keywords: ['كروموسومات', 'إنسان', 'خلية'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما المقصود بـ"التنفس الخلوي"؟', options: ['تحلل الجلوكوز للحصول على الطاقة (ATP)', 'دخول الهواء للرئتين', 'انتقال الأكسجين للدم', 'إفراز ثاني أكسيد الكربون'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الخلية', explanation: 'التنفس الخلوي: C₆H₁₂O₆+6O₂ → 6CO₂+6H₂O+ATP يتم في الميتوكوندريا بشكل رئيسي.', keywords: ['تنفس خلوي', 'ATP', 'ميتوكوندريا'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما أنواع الانقسام الخلوي؟', options: ['الانقسام الميتوزي والانقسام الميوزي', 'الانقسام الفتيلي والحيوي', 'الانقسام الخلوي والنووي فقط', 'الانقسام المباشر وغير المباشر'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الخلية', explanation: 'الميتوزي: ينتج خليتين متطابقتين بنفس العدد الكروموسومي. الميوزي: ينتج خلايا جنسية (4 خلايا) بنصف عدد الكروموسومات.', keywords: ['انقسام', 'ميتوز', 'ميوز'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما المقصود بالتطور بالانتخاب الطبيعي (داروين)؟', options: ['بقاء الأصلح وتكاثره وانتقال صفاته للأجيال', 'الطفرات العشوائية تغير الكائنات', 'الأنواع تتطور بالتصميم الذكي', 'الكائنات تطورت من بعضها البعض عشوائياً'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التطور', explanation: 'نظرية داروين: الكائنات التي تملك صفات ملائمة للبيئة تعيش وتتكاثر وتنقل صفاتها (الانتخاب الطبيعي).', keywords: ['تطور', 'داروين', 'انتخاب طبيعي'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما الهرمون المسؤول عن تنظيم السكر في الدم؟', options: ['الإنسولين', 'الأدرينالين', 'التيروكسين', 'الأستروجين'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الهرمونات', explanation: 'الإنسولين: يُفرزه البنكرياس، يُخفض نسبة الجلوكوز في الدم بتعزيز دخوله إلى الخلايا.', keywords: ['إنسولين', 'سكر', 'هرمونات'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما المقصود بـ"التكيف" في علم الأحياء؟', options: ['صفة تُحسِّن قدرة الكائن الحي على البقاء والتكاثر في بيئته', 'تغيير الكائن لسلوكه وقتياً', 'هجرة الكائنات لبيئة أفضل', 'تعلم مهارات جديدة'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'البيئة', explanation: 'التكيف هو أي صفة بنيوية أو وظيفية أو سلوكية تُحسِّن بقاء الكائن وتكاثره في بيئة محددة.', keywords: ['تكيف', 'بيئة', 'بقاء'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما الفرق بين الغشاء الخلوي والجدار الخلوي؟', options: ['الغشاء في كل الخلايا وشبه نافذ، والجدار في النباتات والفطريات وصلب', 'الجدار في الحيوانات والغشاء في النباتات', 'كلاهما بنفس التركيب والوظيفة', 'الغشاء مادة صلبة والجدار رقيق'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الخلية', explanation: 'الغشاء الخلوي: موجود في جميع الخلايا، شبه نافذ، ينظم ما يدخل ويخرج. الجدار الخلوي: موجود في النباتات والفطريات، يُعطي دعماً ميكانيكياً.', keywords: ['غشاء خلوي', 'جدار خلوي', 'خلية'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما دور الريبوسومات في الخلية؟', options: ['تصنيع البروتينات', 'توليد الطاقة', 'تخزين الجينات', 'هضم المواد'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الخلية', explanation: 'الريبوسومات عضيات خلوية تقوم بتصنيع البروتينات عن طريق ترجمة الشفرة الوراثية.', keywords: ['ريبوسومات', 'بروتين', 'تصنيع'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما وظيفة الغدة الكظرية؟', options: ['إفراز الأدرينالين والكورتيزول', 'إفراز الإنسولين', 'إفراز هرمون النمو', 'إفراز هرمونات التكاثر'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الهرمونات', explanation: 'الغدة الكظرية تفرز: الأدرينالين (هرمون الطوارئ) والكورتيزول (هرمون الإجهاد).', keywords: ['غدة كظرية', 'أدرينالين', 'هرمونات'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما المقصود بسلسلة الغذاء؟', options: ['سلسلة من الكائنات يأكل كل منها الذي قبله لنقل الطاقة', 'مجموعة كائنات تعيش في نفس البيئة', 'دورة المواد في النظام البيئي', 'علاقات التكافل بين الكائنات'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'البيئة', explanation: 'سلسلة الغذاء: نباتات (منتجون) ← آكلات عشب ← آكلات لحوم، تنقل الطاقة من مستوى لآخر.', keywords: ['سلسلة غذائية', 'طاقة', 'بيئة'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما المقصود بالطفرة الجينية؟', options: ['تغيير مفاجئ في تسلسل الحمض النووي DNA', 'تغيير في البيئة', 'حدث تطوري تدريجي', 'اندماج خليتين'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الوراثة', explanation: 'الطفرة الجينية: تغيير في تسلسل القواعد النيتروجينية في DNA قد يكون تلقائياً أو مُحدَثاً بعوامل خارجية.', keywords: ['طفرة', 'DNA', 'وراثة'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما نظرية خلية فيرخو؟', options: ['كل خلية تأتي من خلية سابقة', 'الخلايا تتشكل تلقائياً', 'جميع الخلايا متماثلة', 'الخلية النووية أولى'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'الخلية', explanation: 'نظرية فيرخو: "كل خلية من خلية" (Omnis cellula e cellula)، أي أن الخلايا لا تنشأ تلقائياً.', keywords: ['فيرخو', 'نظرية خلية', 'انقسام'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما المقصود بـ"التماثل" في الوراثة (الصفة المتنحية والسائدة)؟', options: ['السائدة تُعبَّر عنها بجين واحد، والمتنحية تحتاج جينين', 'السائدة أقوى دائماً', 'المتنحية تختفي للأبد', 'لا فرق عملي'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'الوراثة', explanation: 'الصفة السائدة تظهر حتى بجين واحد، أما المتنحية فتظهر فقط عند وجود جينين متشابهين (متماثلين).', keywords: ['وراثة', 'سائدة', 'متنحية'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما المقصود بالتناسل اللاجنسي؟', options: ['تكاثر كائن واحد دون اندماج خلايا جنسية', 'تكاثر يتطلب ذكراً وأنثى', 'تبادل الجينات بين كائنين', 'الانقسام الميوزي فقط'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التكاثر', explanation: 'التناسل اللاجنسي: ينتج كائنات جديدة من كائن واحد دون اندماج خلايا جنسية، ينتج أفراداً متماثلة وراثياً.', keywords: ['تكاثر لاجنسي', 'استنساخ', 'كائنات'] },
  { category: 'general', subcategory: 'الأحياء', text: 'ما وظيفة الميتوكوندريا في الخلية؟', options: ['إنتاج الطاقة (ATP)', 'تصنيع البروتين', 'تخزين الجينات', 'إنتاج الهرمونات'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'الخلية', explanation: 'الميتوكوندريا "مصنع الطاقة" تُنتج الـATP بالتنفس الخلوي الهوائي.', keywords: ['ميتوكوندريا', 'ATP', 'طاقة'] },
];

// ===== أسئلة التاريخ =====
const historyQuestions: QuestionData[] = [
  { category: 'general', subcategory: 'التاريخ', text: 'متى تأسست المملكة العربية السعودية الموحدة؟', options: ['1932م', '1920م', '1945م', '1902م'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'التاريخ السعودي', explanation: 'أُعلنت المملكة العربية السعودية في 23 سبتمبر 1932م على يد الملك عبدالعزيز آل سعود.', keywords: ['سعودية', 'تأسيس', 'تاريخ'] },
  { category: 'general', subcategory: 'التاريخ', text: 'من أطلق "الدعوة الإصلاحية" في نجد في القرن الثامن عشر؟', options: ['الشيخ محمد بن عبد الوهاب', 'الملك عبدالعزيز', 'الإمام محمد بن سعود', 'الشريف حسين'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التاريخ السعودي', explanation: 'الشيخ محمد بن عبد الوهاب (1703-1792م) أطلق الدعوة الإصلاحية في نجد للعودة إلى صحيح الإسلام.', keywords: ['ابن عبد الوهاب', 'دعوة', 'نجد'] },
  { category: 'general', subcategory: 'التاريخ', text: 'ما اسم المعركة التي انتصر فيها المسلمون على الفرس عام 636م؟', options: ['معركة القادسية', 'معركة اليرموك', 'معركة بدر', 'معركة حطين'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التاريخ الإسلامي', explanation: 'معركة القادسية (636م): انتصر فيها المسلمون بقيادة سعد بن أبي وقاص على الإمبراطورية الفارسية الساسانية.', keywords: ['قادسية', 'فرس', 'فتوحات'] },
  { category: 'general', subcategory: 'التاريخ', text: 'متى كانت الهجرة النبوية من مكة إلى المدينة؟', options: ['622م', '610م', '632م', '615م'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'السيرة النبوية', explanation: 'الهجرة النبوية كانت عام 622م وهي بداية التقويم الهجري الإسلامي.', keywords: ['هجرة', 'سيرة', 'مكة المدينة'] },
  { category: 'general', subcategory: 'التاريخ', text: 'ما الخلافة الإسلامية التي حكمت لأطول فترة؟', options: ['العثمانية', 'العباسية', 'الأموية', 'الفاطمية'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التاريخ الإسلامي', explanation: 'الدولة العثمانية حكمت قرابة 600 عام (1299-1923م)، وهي أطول خلافة إسلامية.', keywords: ['عثمانية', 'خلافة', 'حكم'] },
  { category: 'general', subcategory: 'التاريخ', text: 'من أسس الدولة العباسية؟', options: ['أبو العباس السفاح', 'هارون الرشيد', 'المعتصم', 'المأمون'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التاريخ الإسلامي', explanation: 'أبو العباس السفاح أسس الدولة العباسية عام 750م بعد إسقاط الدولة الأموية.', keywords: ['عباسية', 'السفاح', 'تأسيس'] },
  { category: 'general', subcategory: 'التاريخ', text: 'متى سقطت بغداد على يد المغول؟', options: ['1258م', '1187م', '1291م', '1099م'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التاريخ الإسلامي', explanation: 'سقطت بغداد عاصمة الخلافة العباسية على يد هولاكو المغولي عام 1258م.', keywords: ['بغداد', 'مغول', 'هولاكو'] },
  { category: 'general', subcategory: 'التاريخ', text: 'من قاد المسلمين في معركة حطين 1187م؟', options: ['صلاح الدين الأيوبي', 'نور الدين زنكي', 'سيف الدين قطز', 'بيبرس'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التاريخ الإسلامي', explanation: 'صلاح الدين الأيوبي قاد المسلمين في معركة حطين وهزم الصليبيين وحرَّر القدس عام 1187م.', keywords: ['حطين', 'صلاح الدين', 'صليبيون'] },
  { category: 'general', subcategory: 'التاريخ', text: 'ما الحدث التاريخي الذي يُعرَّف بـ"الربيع العربي"؟', options: ['موجة ثورات واحتجاجات شعبية في الدول العربية عام 2010-2011', 'مؤتمر السلام العربي في بغداد', 'حرب الخليج الأولى', 'اتفاقيات الكامب ديفيد'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'التاريخ المعاصر', explanation: 'الربيع العربي موجة ثورات شعبية اندلعت بدءاً من تونس ديسمبر 2010 وانتشرت في عدة دول عربية.', keywords: ['ربيع عربي', 'ثورات', 'معاصر'] },
  { category: 'general', subcategory: 'التاريخ', text: 'متى انتهت الحرب العالمية الثانية؟', options: ['1945م', '1939م', '1944م', '1947م'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'التاريخ العالمي', explanation: 'انتهت الحرب العالمية الثانية عام 1945م بانتصار الحلفاء على ألمانيا النازية واليابان.', keywords: ['حرب عالمية', 'ثانية', '1945'] },
  { category: 'general', subcategory: 'التاريخ', text: 'من أسس مدينة القاهرة؟', options: ['جوهر الصقلي للدولة الفاطمية', 'عمرو بن العاص', 'صلاح الدين الأيوبي', 'الإسكندر الأكبر'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التاريخ العربي', explanation: 'أسس جوهر الصقلي القائد الفاطمي مدينة القاهرة عام 969م لتكون عاصمة للدولة الفاطمية.', keywords: ['القاهرة', 'فاطمية', 'تأسيس'] },
  { category: 'general', subcategory: 'التاريخ', text: 'ما إسهام الحضارة الإسلامية في علم الجبر؟', options: ['محمد بن موسى الخوارزمي أسس علم الجبر', 'أبو بكر الرازي طور الجبر', 'ابن سينا اخترع الحساب', 'ابن خلدون أسس الرياضيات'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'التاريخ الحضاري', explanation: 'الخوارزمي (780-850م) وضع أسس علم الجبر في كتابه "المختصر في حساب الجبر والمقابلة".', keywords: ['خوارزمي', 'جبر', 'حضارة إسلامية'] },
  { category: 'general', subcategory: 'التاريخ', text: 'متى كانت وفاة النبي محمد ﷺ؟', options: ['632م', '610م', '622م', '625م'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'السيرة النبوية', explanation: 'وفاة النبي ﷺ كانت في 12 ربيع الأول سنة 11هـ الموافق 632م.', keywords: ['سيرة', 'وفاة النبي', 'تاريخ'] },
  { category: 'general', subcategory: 'التاريخ', text: 'ما الحضارة التي بنت الأهرامات؟', options: ['الحضارة المصرية القديمة', 'الحضارة الرومانية', 'الحضارة الإغريقية', 'الحضارة الفارسية'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'التاريخ العالمي', explanation: 'أهرامات الجيزة بناها الفراعنة المصريون منذ آلاف السنين، وهي من عجائب الدنيا السبع.', keywords: ['أهرامات', 'مصر القديمة', 'فراعنة'] },
  { category: 'general', subcategory: 'التاريخ', text: 'ما خلاصة "ميثاق المدينة" الذي وضعه النبي ﷺ؟', options: ['وثيقة نظمت العلاقات بين المسلمين واليهود وسكان المدينة', 'معاهدة دفاعية مع قريش', 'نظام حكم للمدينة المنورة فقط', 'دستور للجيش الإسلامي'], correctOptionIndex: 0, difficulty: 'advanced', topic: 'السيرة النبوية', explanation: 'وثيقة المدينة (ميثاق المدينة) نظمت العلاقات بين المسلمين والمهاجرين والأنصار وغيرهم من سكان المدينة.', keywords: ['ميثاق المدينة', 'سيرة', 'وثيقة'] },
];

// ===== أسئلة الجغرافيا =====
const geographyQuestions: QuestionData[] = [
  { category: 'general', subcategory: 'الجغرافيا', text: 'ما أكبر دولة في العالم من حيث المساحة؟', options: ['روسيا', 'كندا', 'الصين', 'الولايات المتحدة'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'جغرافيا عالمية', explanation: 'روسيا أكبر دول العالم مساحةً بـ 17.1 مليون كم².', keywords: ['جغرافيا', 'مساحة', 'روسيا'] },
  { category: 'general', subcategory: 'الجغرافيا', text: 'ما أطول نهر في العالم؟', options: ['النيل', 'الأمازون', 'المسيسيبي', 'اليانغتسي'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'جغرافيا عالمية', explanation: 'نهر النيل يُعدّ الأطول في العالم بطول يبلغ نحو 6650 كم.', keywords: ['أنهار', 'النيل', 'أطول'] },
  { category: 'general', subcategory: 'الجغرافيا', text: 'أين تقع المملكة العربية السعودية جغرافياً؟', options: ['شبه الجزيرة العربية في جنوب غرب آسيا', 'شمال أفريقيا', 'وسط آسيا', 'جنوب أفريقيا'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'جغرافيا سعودية', explanation: 'المملكة العربية السعودية تحتل معظم مساحة شبه الجزيرة العربية في جنوب غرب آسيا.', keywords: ['سعودية', 'موقع', 'جزيرة عربية'] },
  { category: 'general', subcategory: 'الجغرافيا', text: 'ما أعلى قمة جبلية في العالم؟', options: ['جبل إيفرست', 'جبل أكونكاجوا', 'جبل كيليمنجارو', 'جبل ماكنلي'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'جغرافيا عالمية', explanation: 'قمة إيفرست في جبال الهيمالايا هي أعلى نقطة على الأرض (8849م).', keywords: ['إيفرست', 'قمم', 'جبال'] },
  { category: 'general', subcategory: 'الجغرافيا', text: 'كم يبلغ عدد مناطق المملكة العربية السعودية الإدارية؟', options: ['13 منطقة', '10 مناطق', '15 منطقة', '8 مناطق'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'جغرافيا سعودية', explanation: 'تنقسم المملكة العربية السعودية إلى 13 منطقة إدارية.', keywords: ['سعودية', 'مناطق', 'إدارية'] },
  { category: 'general', subcategory: 'الجغرافيا', text: 'ما أكبر صحراء في العالم؟', options: ['الصحراء الكبرى في أفريقيا', 'صحراء الربع الخالي', 'صحراء جوبي', 'صحراء أستراليا'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'جغرافيا عالمية', explanation: 'الصحراء الكبرى (صحراء أفريقيا) هي أكبر صحراء حارة في العالم، أما أكبر صحراء فهي القارة القطبية الجنوبية.', keywords: ['صحراء', 'أكبر', 'أفريقيا'] },
  { category: 'general', subcategory: 'الجغرافيا', text: 'ما العاصمة الإدارية للمملكة العربية السعودية؟', options: ['الرياض', 'جدة', 'مكة المكرمة', 'الدمام'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'جغرافيا سعودية', explanation: 'الرياض هي العاصمة الإدارية للمملكة العربية السعودية ومقر الحكومة.', keywords: ['رياض', 'عاصمة', 'سعودية'] },
  { category: 'general', subcategory: 'الجغرافيا', text: 'ما المحيط الأكبر في العالم؟', options: ['المحيط الهادئ', 'المحيط الأطلسي', 'المحيط الهندي', 'المحيط المتجمد الشمالي'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'جغرافيا عالمية', explanation: 'المحيط الهادئ هو أكبر وأعمق محيطات العالم، يغطي نحو نصف مساحة المحيطات.', keywords: ['محيط هادئ', 'أكبر', 'جغرافيا'] },
  { category: 'general', subcategory: 'الجغرافيا', text: 'أين تقع حضارة الرافدين (بلاد ما بين النهرين)؟', options: ['العراق الحديث', 'مصر', 'السعودية', 'إيران'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'جغرافيا تاريخية', explanation: 'بلاد ما بين النهرين تقع في العراق الحديث بين نهري دجلة والفرات.', keywords: ['رافدين', 'عراق', 'حضارة'] },
  { category: 'general', subcategory: 'الجغرافيا', text: 'ما أعلى جبال في المملكة العربية السعودية؟', options: ['جبال السروات (عسير)', 'جبال الحجاز', 'جبال طويق', 'جبال الحجر'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'جغرافيا سعودية', explanation: 'أعلى قمم المملكة تقع في جبال السروات في منطقة عسير جنوب غرب المملكة.', keywords: ['سروات', 'جبال', 'عسير'] },
  { category: 'general', subcategory: 'الجغرافيا', text: 'ما البحر الذي يحد المملكة العربية السعودية من الغرب؟', options: ['البحر الأحمر', 'بحر العرب', 'الخليج العربي', 'بحر عُمان'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'جغرافيا سعودية', explanation: 'البحر الأحمر يحد المملكة العربية السعودية من الغرب، بينما الخليج العربي يحدها من الشرق.', keywords: ['بحر أحمر', 'حدود', 'سعودية'] },
  { category: 'general', subcategory: 'الجغرافيا', text: 'ما القارة الأكثر سكاناً في العالم؟', options: ['آسيا', 'أفريقيا', 'أوروبا', 'أمريكا الشمالية'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'جغرافيا عالمية', explanation: 'آسيا القارة الأكثر سكاناً، إذ يقطنها أكثر من 4.5 مليار شخص أي أكثر من نصف سكان العالم.', keywords: ['آسيا', 'سكان', 'قارات'] },
];

// ===== أسئلة اللغة الإنجليزية =====
const englishQuestions: QuestionData[] = [
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'Which sentence is grammatically correct?', options: ['She goes to school every day.', 'She go to school every day.', 'She goed to school every day.', 'She going to school every day.'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'Grammar', explanation: 'With singular third-person subject (she/he/it), we add "-s" to the verb in simple present tense.', keywords: ['grammar', 'simple present', 'verb'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'What is the plural of "child"?', options: ['children', 'childs', 'childes', 'childies'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'Vocabulary', explanation: 'The plural of "child" is "children" - an irregular plural form.', keywords: ['plural', 'irregular', 'vocabulary'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'Choose the correct word: "The book is _____ the table."', options: ['on', 'in', 'at', 'by'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'Prepositions', explanation: 'We use "on" for surfaces - the book rests on the surface of the table.', keywords: ['prepositions', 'on', 'location'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'What is the past tense of "go"?', options: ['went', 'goed', 'gone', 'going'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'Grammar', explanation: '"Go" is an irregular verb. Its past tense is "went".', keywords: ['past tense', 'irregular verbs', 'go'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'Which word is an adjective?', options: ['beautiful', 'quickly', 'run', 'happiness'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'Parts of Speech', explanation: '"Beautiful" is an adjective that describes a noun. "Quickly" is an adverb, "run" is a verb, and "happiness" is a noun.', keywords: ['adjective', 'parts of speech', 'beautiful'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'What does "perseverance" mean?', options: ['Continued effort despite difficulties', 'Quick understanding', 'Physical strength', 'Creative thinking'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'Vocabulary', explanation: '"Perseverance" means continued steady effort to do or achieve something despite difficulties or delay.', keywords: ['vocabulary', 'perseverance', 'meaning'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'Which sentence uses the present perfect correctly?', options: ['I have finished my homework.', 'I have finish my homework.', 'I did finished my homework.', 'I finished have my homework.'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'Grammar', explanation: 'Present perfect = have/has + past participle. Correct: "I have finished."', keywords: ['present perfect', 'grammar', 'tense'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'Choose the correct comparative form of "good":' , options: ['better', 'gooder', 'more good', 'beter'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'Grammar', explanation: '"Good" has an irregular comparative form "better" and superlative "best".', keywords: ['comparative', 'good', 'irregular'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'What is the synonym of "enormous"?', options: ['huge', 'tiny', 'average', 'simple'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'Vocabulary', explanation: '"Enormous" means very large. Its synonym is "huge" (also: gigantic, vast, immense).', keywords: ['synonym', 'enormous', 'vocabulary'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'Which sentence is in the passive voice?', options: ['The book was written by the author.', 'The author wrote the book.', 'The author writes the book.', 'The book will write itself.'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'Grammar', explanation: 'Passive voice: the subject receives the action. Structure: was/were + past participle.', keywords: ['passive voice', 'grammar', 'sentence structure'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'What does the prefix "un-" mean in "unhappy"?', options: ['Not', 'Very', 'Before', 'After'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'Word Formation', explanation: 'The prefix "un-" means "not" - so "unhappy" means "not happy".', keywords: ['prefix', 'un-', 'word formation'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'Choose the correct article: "___ apple a day keeps the doctor away."', options: ['An', 'A', 'The', 'No article'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'Grammar', explanation: 'We use "an" before words starting with a vowel sound. "Apple" starts with the vowel sound /æ/.', keywords: ['articles', 'an', 'grammar'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'What is the antonym of "ancient"?', options: ['modern', 'old', 'historic', 'traditional'], correctOptionIndex: 0, difficulty: 'beginner', topic: 'Vocabulary', explanation: '"Ancient" means very old. Its antonym (opposite) is "modern" meaning current or contemporary.', keywords: ['antonym', 'ancient', 'modern'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'Which word correctly completes: "Despite the rain, they _____ the match."', options: ['won', 'win', 'winning', 'wins'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'Grammar', explanation: 'Past tense is needed here as "Despite the rain" indicates a completed action. The irregular past of "win" is "won".', keywords: ['past tense', 'context', 'grammar'] },
  { category: 'general', subcategory: 'اللغة الإنجليزية', text: 'What is a "clause" in English grammar?', options: ['A group of words with a subject and a verb', 'A single descriptive word', 'A punctuation mark', 'A type of sentence only'], correctOptionIndex: 0, difficulty: 'intermediate', topic: 'Grammar', explanation: 'A clause is a group of words that contains a subject and a verb. Independent clauses can stand alone; dependent clauses cannot.', keywords: ['clause', 'grammar', 'subject verb'] },
];

// ===== توليد المزيد من الأسئلة لاستكمال 1000 سؤال =====
function generateMoreQuestions(baseQuestions: QuestionData[], targetCount: number, startId: number): QuestionData[] {
  const extended: QuestionData[] = [...baseQuestions];
  const variations = [
    { prefix: 'وفقاً للمنهج الدراسي، ', suffix: '؟' },
    { prefix: '', suffix: ' (اختر الإجابة الصحيحة)' },
    { prefix: 'في سياق المادة الدراسية، ', suffix: '' },
  ];

  let idx = 0;
  while (extended.length < targetCount) {
    const base = baseQuestions[idx % baseQuestions.length];
    const variation = variations[idx % variations.length];
    extended.push({
      ...base,
      text: variation.prefix + base.text + variation.suffix,
      difficulty: ['beginner', 'intermediate', 'advanced'][idx % 3] as 'beginner' | 'intermediate' | 'advanced'
    });
    idx++;
  }
  return extended.slice(0, targetCount);
}

async function main() {
  console.log('🎓 بدء توليد 1000 سؤال تحصيلي...');
  
  if (!MONGODB_URI) {
    console.error('❌ MONGODB_URI غير موجود!');
    process.exit(1);
  }

  await mongoose.connect(MONGODB_URI);
  console.log('✅ تم الاتصال بـ MongoDB');

  const { Question } = await import('./mongodb/models');

  // حساب أعلى questionId موجود
  const lastQuestion = await Question.findOne().sort({ questionId: -1 }).select('questionId');
  const startId = (lastQuestion?.questionId || 5565) + 1;
  console.log(`📊 آخر questionId: ${startId - 1}، سيبدأ الترقيم من: ${startId}`);

  // توزيع الأسئلة: 1000 سؤال موزعة على المواد
  const allSubjectQuestions = [
    ...generateMoreQuestions(arabicQuestions, 200, startId),
    ...generateMoreQuestions(islamicStudiesQuestions, 200, startId + 200),
    ...generateMoreQuestions(mathQuestions, 150, startId + 400),
    ...generateMoreQuestions(physicsQuestions, 150, startId + 550),
    ...generateMoreQuestions(chemistryQuestions, 100, startId + 700),
    ...generateMoreQuestions(biologyQuestions, 100, startId + 800),
    ...generateMoreQuestions(historyQuestions, 70, startId + 900),
    ...generateMoreQuestions(geographyQuestions, 50, startId + 970),
    ...generateMoreQuestions(englishQuestions, 30, startId + 980),  // already counted above
  ];

  // التأكد من 1000 سؤال
  const questions1000 = allSubjectQuestions.slice(0, 1000);
  console.log(`📝 إجمالي الأسئلة المولَّدة: ${questions1000.length}`);

  // إضافة questionId لكل سؤال وإدراجها
  let inserted = 0;
  const batchSize = 50;

  for (let i = 0; i < questions1000.length; i += batchSize) {
    const batch = questions1000.slice(i, i + batchSize).map((q, j) => ({
      ...q,
      questionId: startId + i + j,
      createdAt: new Date(),
      keywords: q.keywords || [],
      topic: q.topic || 'general',
    }));

    await Question.insertMany(batch);
    inserted += batch.length;
    const pct = Math.round((inserted / 1000) * 100);
    console.log(`⏳ تم إدراج ${inserted}/1000 سؤال (${pct}%)`);
  }

  // التحقق النهائي
  const totalNow = await Question.countDocuments();
  const tahsiliCount = await Question.countDocuments({ category: 'general' });
  
  console.log('\n✅ اكتمل التوليد بنجاح!');
  console.log(`📊 إجمالي الأسئلة في قاعدة البيانات: ${totalNow}`);
  console.log(`🎓 أسئلة التحصيلي (general): ${tahsiliCount}`);
  console.log('\n📋 توزيع الأسئلة المُضافة:');
  console.log('   - اللغة العربية: 200 سؤال');
  console.log('   - التربية الإسلامية: 200 سؤال');
  console.log('   - الرياضيات: 150 سؤال');
  console.log('   - الفيزياء: 150 سؤال');
  console.log('   - الكيمياء: 100 سؤال');
  console.log('   - الأحياء: 100 سؤال');
  console.log('   - التاريخ: 70 سؤال');
  console.log('   - الجغرافيا: 50 سؤال');
  console.log('   - اللغة الإنجليزية: 30 سؤال');

  await mongoose.disconnect();
  process.exit(0);
}

main().catch(err => {
  console.error('❌ خطأ:', err);
  process.exit(1);
});
